# Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    base_yaw_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint:  base_yaw_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    fix_waist_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: fix_waist_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    waist_body_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: waist_body_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    # To add more just add them here as the first one
    waist_roll_aux_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: waist_roll_aux_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    roll_yaw2_aux_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_yaw2_aux_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    



